---
title: "Donnermeyer_Homework_5"
author: "Sam Donnermeyer"
date: "10/9/2020"
output:
  pdf_document: default
  html_document: default
---

## Hand In Homework #4


### Problem #1: Sampling Problems (Questions 2 & 3)

***
#### **(2)** 
A researcher wishes to estimate the total number of users of a trail head over the course of 15 weeks. She randomly selects 3 Mondays, 3 Tuesdays, 3 Wednesdays, 3 Thursdays, 3 Fridays, 5 Saturdays and 5 Sundays from the whole 15-week period and stations an observer there on each selected day. The observer records the number of trail users for the day.

Population: 
 - All users of a the trail head over the course of the given 15 weeks. 

Sampling Units: 
 - Trail users (people). 

Sampling Plan: 
 - Multistage 
    - Stratified Random Sampling (To Identify which days to select) -> Cluster Sampling (Sample All Trail Users that Day)

***
#### **(3)** 
In the previous problem, the researcher would also like to estimate the proportion of trail users who are from out of state. The observer also records where each trail user is from.

Population: 
 - All users of the trail head over the course of the given 15 weeks who are from out of state.
 
Sampling Units: 
 - Trail users (people). 

Sampling Plan: 
 - Multistage 
    - Stratified Random Sampling (To Identify which days to select) -> Cluster Sampling (Sample All Trail Users that Day)

### Problem #2: Part III Review Exercises (pp. 373-378): R.3.10, R.3.12, R.3.16, R.3.28, R.3.32
Analyze the design of each research example reported. Is it a sample survey, an observational study, or an experiment? If a sample, what are the population, the parameter of interest, and the sampling procedure? If an observational study, was it retrospective or prospective? If an experiment, describe the factors, treatments, randomization, response variable, and any blocking, matching, or blinding that may be present. In each, what kind of conclusions can be reached? 

#### R.3.10
The study detailed in the problem is a retrospective observational study because the men who had prostate cancer were identified through an existing cancer registry. There seems to be strong evidence that men who have vasectomies is connected to developing prostate cancer. 

#### R.3.12
This is an experiment with the factors, glaze and the temperatures the pottery was baked at. The different treatments available are the four types of glazes and the three different temperature settings in the kiln. There was no randomization included in this experiment. The response variable is the 'appearance of age' in the newly made pottery. There was no blocking, matching, or blinding present in the experiment. Based on the results of the experiment, the potter can determine which combination of factors and treatments creates pottery that appears to be aged. 

#### R.3.16
The scenario detailed is a sample survey, where the population is all soda bottles produced by the soft-drink manufacturer and the parameter of interest is strength of the caps on the newly bottled soda. 

#### R.3.28
a) The factors are the cooking times (levels: 10 & 15 minutes), different cooking temperatures (levels: 325, 375, and 425 degrees F), and the amount of chocolate chips in each cookie (levels: 5 or 10). 

b) Blinding in the context of this experiment means the evaluators (the six friends) are unaware of the different levels in each of the factors in order to prevent any bias from entering the evaluation. It is not double blinded because Mary Beth, NIgel, and Molly know what types of cookies they are servering and have made in order to evaluate them properly after the six friends give their feedback. 

c) Each judge will taste 12 different cookies in order to be exposed to all levels of each factor.

d) The response variable will be ordinal, to show the order in which the judges deem the cookies to be in, to rank the cookies from from best to worse.

e) The challenges of the experiment is the resources to make 72 cookies (12 for each judge) and carry out the processes correctly and consistently, essentially the reproducability of each type of cookie. Secondly, the judge's might not be able to differentiate between the cookies enough to give any meaningful information regarding the best cookie combination. 

#### R.3.32
a) This is an experiment which has a block, which is the sex of the volunteer. 

b) No, the experiment is to resolve the effectiveness of the treatment among those who suffer from reflux disease, and since all volunteers are suffering from reflux disease, the experiment can determine if the treatment aids the reflux disease. 

c) The use of a placebo would make the volunteers blind to the treatment that they are receiving. This would allow for the results from the antacid to be vetted. 

